server:
  port: 8012
  context-path: /VLT

vlt.settings:
  pathsUploadedFiles: VLabs
  framesXml: LaboratoryFrames.xml

spring:
  http:
       multipart:
           max-file-size: 512MB
           max-request-size: 5124MB

security.token:
  tokenExpirationTime: 30 # Minutes
  refreshTokenExpTime: 1440 # Minutes
  tokenIssuer: http://efimchick.com
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

spring.datasource:
  url: "jdbc:h2:~/vltDB"
  driverClassName: org.h2.Driver
  username: "admin"
  password: "peterthegreat"

spring.jpa:
  database: H2
  show-sql: true
  database-platform: com.spring.boot.vlt.config.H2ExtDialect
  hibernate.ddl-auto: none # use "create" for auto create data base

spring.h2.console.enabled: true
